% Drag node 18 along the current panel normal and correct each step by LM.
clear;
clc;
close all;

codeDir = fileparts(mfilename('fullpath'));
modelFile = fullfile(codeDir,'four_panel_reference.mat');

%% Settings
dragNode = 18;
dragStepLength = 0.05;
nDragSteps = 130;
regularization = 1e-7;
maximumRotationAngle = deg2rad(180);
constraintRankTolerance = 1e-10;

if dragStepLength <= 0 || nDragSteps < 1 || ...
        nDragSteps ~= round(nDragSteps) || regularization <= 0 || ...
        maximumRotationAngle <= 0 || ~isfinite(maximumRotationAngle)
    error('demo_miura_drag:InvalidDrag', ...
        ['Step length, step count, and regularization must be positive; ' ...
         'the rotation-angle limit must be finite and positive.']);
end

%% Zero-displacement model
model = load(modelFile,'x0','y0','z0','B','T', ...
    'mainPointIndices','fix','panels');
x0 = model.x0(:);
y0 = model.y0(:);
z0 = model.z0(:);
mainPointIndices = model.mainPointIndices(:).';
fixedNodes = model.fix(:).';
panels = model.panels;

mappedBFull = model.T\model.B;
[~,fixedMasterLocalIndices] = ismember(fixedNodes,mainPointIndices);
freeMasterLocalIndices = setdiff(1:numel(mainPointIndices), ...
    fixedMasterLocalIndices,'stable');
dragMasterLocalIndex = find(mainPointIndices == dragNode,1);
dragMasterFreeIndex = find( ...
    freeMasterLocalIndices == dragMasterLocalIndex,1);
if isempty(dragMasterLocalIndex) || isempty(dragMasterFreeIndex)
    error('demo_miura_drag:InvalidDragNode', ...
        'dragNode must be an unfixed master node.');
end

mappedB = mappedBFull(:,freeMasterLocalIndices);
nFreeMasters = size(mappedB,2);
dragDofIndices = dragMasterFreeIndex+[0,nFreeMasters,2*nFreeMasters];

% Select panel metric constraints once in the full compatible affine space.
panelNodes = cellfun(@(panelFaces) unique([panelFaces{:}],'stable'), ...
    panels,'UniformOutput',false);
[rigidityDirectionsFull,rigidityReferences,rigidityOffsets, ...
    metricConstraints,candidateMetricConstraints] = ...
    AffineMetricConstraintFactors(mappedBFull,x0,y0,z0,panelNodes,3, ...
    constraintRankTolerance);
rigidityDirections = ...
    rigidityDirectionsFull(:,freeMasterLocalIndices,:);
fprintf('Thick-panel metric constraints: %d preset, %d independent.\n', ...
    size(candidateMetricConstraints,1),size(metricConstraints,1));

% Nodes 17-18-24 form the broad surface containing the dragged node.
normalFaceNodes = [17 18 24];

% Each row defines the two panels adjacent to one physical hinge.
rotationNodeIndices = [16 17 24 18; ...
    11 12 21 13; ...
    14 15 20 10; ...
    2 19 1 9];
rotationEdges = rotationNodeIndices(:,2:3);
rotationAngleTolerance = deg2rad(1e-8);
angleBoundaryTolerance = deg2rad(0.1);
maximumAngleBisections = 30;

%% Perturbation correction
nNodes = numel(x0);
if any(rotationNodeIndices(:) < 1 | rotationNodeIndices(:) > nNodes)
    error('demo_miura_drag:InvalidRotationNodes', ...
        'A rotation-angle constraint contains an invalid node index.');
end
rotationAngles = RotationAngle( ...
    size(rotationNodeIndices,1),rotationNodeIndices,x0,y0,z0);
if any(abs(rotationAngles) > ...
        maximumRotationAngle+rotationAngleTolerance)
    error('demo_miura_drag:InitialRotationViolation', ...
        'The initial model already exceeds the rotation-angle limit.');
end

xHistory = zeros(nNodes,nDragSteps+1);
yHistory = zeros(nNodes,nDragSteps+1);
zHistory = zeros(nNodes,nDragSteps+1);
xHistory(:,1) = x0;
yHistory(:,1) = y0;
zHistory(:,1) = z0;

coordinates = [x0,y0,z0];
masterDisplacement = zeros(3*nFreeMasters,1);
previousPanelNormal = [];
maximumResidual = 0;
maximumAcceptedRotationAngle = max(abs(rotationAngles));
angleLimitReached = false;
completedSteps = 0;
rejectedRotationAngle = NaN;
rejectedRotationEdge = [NaN NaN];
boundaryRotationAngle = NaN;
boundaryStepLength = NaN;
solverOptions = struct('Regularization',regularization, ...
    'ConstraintTolerance',1e-8,'MaxIterations',150);
correctionStepLength = dragStepLength;
minimumCorrectionStepLength = dragStepLength/2^20;

solveTimer = tic;
for stepIndex = 1:nDragSteps
    remainingStepLength = dragStepLength;
    substepCount = 0;
    stepMaximumResidual = 0;
    stepMaximumRotationAngle = 0;
    while remainingStepLength > 10*eps(dragStepLength)
        trialStepLength = min(correctionStepLength,remainingStepLength);
        faceCoordinates = coordinates(normalFaceNodes,:);
        panelNormal = cross( ...
            faceCoordinates(2,:)-faceCoordinates(1,:), ...
            faceCoordinates(3,:)-faceCoordinates(1,:));
        panelNormal = panelNormal/norm(panelNormal);
        if ~isempty(previousPanelNormal) && ...
                dot(panelNormal,previousPanelNormal) < 0
            panelNormal = -panelNormal;
        end
        targetMasterDisplacement = masterDisplacement;
        targetMasterDisplacement(dragDofIndices) = ...
            targetMasterDisplacement(dragDofIndices) ...
            +trialStepLength*panelNormal(:);
        [trialMasterDisplacement,solverInfo] = MiuraPerturbCorrect( ...
            targetMasterDisplacement,rigidityDirections, ...
            rigidityReferences,rigidityOffsets,solverOptions);

        if solverInfo.exitflag > 0 && solverInfo.constraintSatisfied
            trialCoordinates = [x0,y0,z0] ...
                +mappedB*reshape( ...
                trialMasterDisplacement,nFreeMasters,3);
            principalRotationAngles = RotationAngle( ...
                size(rotationNodeIndices,1),rotationNodeIndices, ...
                trialCoordinates(:,1),trialCoordinates(:,2), ...
                trialCoordinates(:,3));
            rotationAngleIncrement = atan2( ...
                sin(principalRotationAngles-rotationAngles), ...
                cos(principalRotationAngles-rotationAngles));
            trialRotationAngles = rotationAngles+rotationAngleIncrement;
            [trialMaximumRotationAngle,rotationIndex] = max( ...
                abs(trialRotationAngles));
            if trialMaximumRotationAngle > ...
                    maximumRotationAngle+rotationAngleTolerance
                rejectedRotationAngle = trialMaximumRotationAngle;

                % Bisect the perturbation and rerun LM to reach the angle boundary.
                angleBaseMasterDisplacement = masterDisplacement;
                angleBaseRotationAngles = rotationAngles;
                lowerStepLength = 0;
                upperStepLength = trialStepLength;
                boundaryMasterDisplacement = masterDisplacement;
                boundaryCoordinates = coordinates;
                boundaryRotationAngles = rotationAngles;
                boundaryMaximumRotationAngle = max(abs(rotationAngles));
                boundaryRotationIndex = rotationIndex;
                boundaryResidual = 0;
                for angleBisectionIndex = 1:maximumAngleBisections
                    candidateStepLength = 0.5*( ...
                        lowerStepLength+upperStepLength);
                    candidateTargetMasterDisplacement = ...
                        angleBaseMasterDisplacement;
                    candidateTargetMasterDisplacement(dragDofIndices) = ...
                        candidateTargetMasterDisplacement(dragDofIndices) ...
                        +candidateStepLength*panelNormal(:);
                    [candidateMasterDisplacement,candidateSolverInfo] = ...
                        MiuraPerturbCorrect( ...
                        candidateTargetMasterDisplacement, ...
                        rigidityDirections,rigidityReferences, ...
                        rigidityOffsets,solverOptions);
                    if candidateSolverInfo.exitflag <= 0 || ...
                            ~candidateSolverInfo.constraintSatisfied
                        error('demo_miura_drag:AngleBoundaryCorrectionFailed', ...
                            ['LM failed while locating the angle boundary ' ...
                             'at step %d.'],stepIndex);
                    end

                    candidateCoordinates = [x0,y0,z0] ...
                        +mappedB*reshape( ...
                        candidateMasterDisplacement,nFreeMasters,3);
                    candidatePrincipalAngles = RotationAngle( ...
                        size(rotationNodeIndices,1), ...
                        rotationNodeIndices,candidateCoordinates(:,1), ...
                        candidateCoordinates(:,2), ...
                        candidateCoordinates(:,3));
                    candidateAngleIncrement = atan2( ...
                        sin(candidatePrincipalAngles ...
                        -angleBaseRotationAngles), ...
                        cos(candidatePrincipalAngles ...
                        -angleBaseRotationAngles));
                    candidateRotationAngles = angleBaseRotationAngles ...
                        +candidateAngleIncrement;
                    [candidateMaximumRotationAngle, ...
                        candidateRotationIndex] = max( ...
                        abs(candidateRotationAngles));

                    if candidateMaximumRotationAngle ...
                            <= maximumRotationAngle
                        lowerStepLength = candidateStepLength;
                        boundaryMasterDisplacement = ...
                            candidateMasterDisplacement;
                        boundaryCoordinates = candidateCoordinates;
                        boundaryRotationAngles = ...
                            candidateRotationAngles;
                        boundaryMaximumRotationAngle = ...
                            candidateMaximumRotationAngle;
                        boundaryRotationIndex = candidateRotationIndex;
                        boundaryResidual = candidateSolverInfo.maxResidual;
                        if maximumRotationAngle ...
                                -boundaryMaximumRotationAngle ...
                                <= angleBoundaryTolerance
                            break
                        end
                    else
                        upperStepLength = candidateStepLength;
                    end
                end

                if maximumRotationAngle-boundaryMaximumRotationAngle ...
                        > angleBoundaryTolerance
                    error('demo_miura_drag:AngleBoundaryFailed', ...
                        ['The final angle at step %d is more than 0.1 ' ...
                         'degree below the limit.'],stepIndex);
                end

                masterDisplacement = boundaryMasterDisplacement;
                coordinates = boundaryCoordinates;
                previousPanelNormal = panelNormal;
                rotationAngles = boundaryRotationAngles;
                angleLimitReached = true;
                boundaryRotationAngle = boundaryMaximumRotationAngle;
                boundaryStepLength = lowerStepLength;
                rejectedRotationEdge = ...
                    rotationEdges(boundaryRotationIndex,:);
                substepCount = substepCount+1;
                stepMaximumResidual = max( ...
                    stepMaximumResidual,boundaryResidual);
                stepMaximumRotationAngle = max( ...
                    stepMaximumRotationAngle,boundaryRotationAngle);
                fprintf(['Step %d reached hinge [%d %d] limit at ' ...
                    '%.3f deg using a partial step %.6g; ' ...
                    'the %.3f deg trial was not accepted.\n'], ...
                    stepIndex,rejectedRotationEdge(1), ...
                    rejectedRotationEdge(2), ...
                    rad2deg(boundaryRotationAngle), ...
                    boundaryStepLength,rad2deg(rejectedRotationAngle));
                break
            end

            masterDisplacement = trialMasterDisplacement;
            coordinates = trialCoordinates;
            previousPanelNormal = panelNormal;
            rotationAngles = trialRotationAngles;
            remainingStepLength = max(0, ...
                remainingStepLength-trialStepLength);
            substepCount = substepCount+1;
            stepMaximumResidual = max( ...
                stepMaximumResidual,solverInfo.maxResidual);
            stepMaximumRotationAngle = max( ...
                stepMaximumRotationAngle,trialMaximumRotationAngle);
        else
            correctionStepLength = trialStepLength/2;
            if correctionStepLength < minimumCorrectionStepLength
                error('demo_miura_drag:CorrectionFailed', ...
                    ['Step %d failed after adaptive subdivision: ' ...
                     'exitflag=%d, max|c|=%.3e.'], ...
                    stepIndex,solverInfo.exitflag,solverInfo.maxResidual);
            end
        end
    end

    xHistory(:,stepIndex+1) = coordinates(:,1);
    yHistory(:,stepIndex+1) = coordinates(:,2);
    zHistory(:,stepIndex+1) = coordinates(:,3);
    completedSteps = stepIndex;
    maximumResidual = max(maximumResidual,stepMaximumResidual);
    maximumAcceptedRotationAngle = max( ...
        maximumAcceptedRotationAngle,stepMaximumRotationAngle);

    fprintf(['Step %d/%d: %d LM substeps, correction step %.4g, ' ...
        'max|c| %.3e, max angle %.3f deg\n'], ...
        stepIndex,nDragSteps,substepCount,correctionStepLength, ...
        stepMaximumResidual,rad2deg(stepMaximumRotationAngle));
    if angleLimitReached
        break
    end
end
solveTime = toc(solveTimer);

xHistory = xHistory(:,1:completedSteps+1);
yHistory = yHistory(:,1:completedSteps+1);
zHistory = zHistory(:,1:completedSteps+1);
x_fs = xHistory(:,end);
y_fs = yHistory(:,end);
z_fs = zHistory(:,end);
fprintf(['Finished %d/%d accepted steps in %.3f s; max|c| %.3e, ' ...
    'max angle %.3f deg.\n'],completedSteps,nDragSteps,solveTime, ...
    maximumResidual,rad2deg(maximumAcceptedRotationAngle));

%% Animation
xLimits = [min(xHistory(:)),max(xHistory(:))];
yLimits = [min(yHistory(:)),max(yHistory(:))];
zLimits = [min(zHistory(:)),max(zHistory(:))];
padding = 0.1*max([diff(xLimits),diff(yLimits),diff(zLimits)]);
xLimits = xLimits+[-padding padding];
yLimits = yLimits+[-padding padding];
zLimits = zLimits+[-padding padding];

animationFigure = figure('Color','w','Name','Miura node 18 drag', ...
    'NumberTitle','off');
animationAxes = axes(animationFigure);
axes(animationAxes);
panelHandles = DrawSolidPanels(xHistory(:,1),yHistory(:,1), ...
    zHistory(:,1),panels,'FaceAlpha',0.56,'LineWidth',1.0);
faceNodes = [panels{:}];
hold(animationAxes,'on');
fixedHandle = scatter3(animationAxes,xHistory(fixedNodes,1), ...
    yHistory(fixedNodes,1),zHistory(fixedNodes,1),80, ...
    [0.08 0.08 0.08],'filled','MarkerEdgeColor','w');
dragHandle = scatter3(animationAxes,xHistory(dragNode,1), ...
    yHistory(dragNode,1),zHistory(dragNode,1),150, ...
    [0.02 0.48 0.95],'filled','MarkerEdgeColor','w');
faceCoordinates = [xHistory(normalFaceNodes,1), ...
    yHistory(normalFaceNodes,1),zHistory(normalFaceNodes,1)];
arrowDirection = cross( ...
    faceCoordinates(2,:)-faceCoordinates(1,:), ...
    faceCoordinates(3,:)-faceCoordinates(1,:));
arrowDirection = padding*arrowDirection/norm(arrowDirection);
tractionHandle = quiver3(animationAxes,xHistory(dragNode,1), ...
    yHistory(dragNode,1),zHistory(dragNode,1), ...
    arrowDirection(1),arrowDirection(2),arrowDirection(3),0, ...
    'Color','r','LineWidth',2.5,'MaxHeadSize',0.8);
hold(animationAxes,'off');
axis(animationAxes,'equal');
axis(animationAxes,'vis3d');
axis(animationAxes,'off');
view(animationAxes,210,24);
xlim(animationAxes,xLimits);
ylim(animationAxes,yLimits);
zlim(animationAxes,zLimits);

for historyIndex = 1:completedSteps+1
    for faceIndex = 1:numel(faceNodes)
        nodes = faceNodes{faceIndex};
        set(panelHandles(faceIndex), ...
            'XData',xHistory(nodes,historyIndex), ...
            'YData',yHistory(nodes,historyIndex), ...
            'ZData',zHistory(nodes,historyIndex));
    end
    set(fixedHandle, ...
        'XData',xHistory(fixedNodes,historyIndex), ...
        'YData',yHistory(fixedNodes,historyIndex), ...
        'ZData',zHistory(fixedNodes,historyIndex));
    set(dragHandle, ...
        'XData',xHistory(dragNode,historyIndex), ...
        'YData',yHistory(dragNode,historyIndex), ...
        'ZData',zHistory(dragNode,historyIndex));
    faceCoordinates = [xHistory(normalFaceNodes,historyIndex), ...
        yHistory(normalFaceNodes,historyIndex), ...
        zHistory(normalFaceNodes,historyIndex)];
    arrowDirection = cross( ...
        faceCoordinates(2,:)-faceCoordinates(1,:), ...
        faceCoordinates(3,:)-faceCoordinates(1,:));
    arrowDirection = padding*arrowDirection/norm(arrowDirection);
    set(tractionHandle, ...
        'XData',xHistory(dragNode,historyIndex), ...
        'YData',yHistory(dragNode,historyIndex), ...
        'ZData',zHistory(dragNode,historyIndex), ...
        'UData',arrowDirection(1), ...
        'VData',arrowDirection(2), ...
        'WData',arrowDirection(3));
    title(animationAxes,sprintf('Node %d: step %d/%d', ...
        dragNode,historyIndex-1,nDragSteps));
    drawnow;
end
