function f = equalityPenaltyObjective(beta,equalityPenalty, ...
    rigidityDirections,rigidityReferences,rigidityOffsets)
ceq = AffineMetricResidualJacobian(beta,rigidityDirections, ...
    rigidityReferences,rigidityOffsets);
f = 0.5 * equalityPenalty * sum(ceq.^2);
end
