function f = equalityPenaltyObjective(beta,~,equalityPenalty, ...
    x0,y0,z0,B,rigidityDirections,rigidityReferences,rigidityOffsets, ...
    Cchi,Cfold,r,T,chiMargin,foldAngleMargin)
[~, ceq] = ConstraintsGen(beta,x0,y0,z0,B,rigidityDirections, ...
    rigidityReferences,rigidityOffsets,Cchi,Cfold,r,T, ...
    chiMargin,foldAngleMargin);
f = 0.5 * equalityPenalty * sum(ceq.^2);

end
