function jacobian = EvaluateLowRankJacobian( ...
    projectedU,projectedV,directionU,directionV,referenceU,referenceV)
% Assemble the analytic Jacobian from projections already evaluated at this state.
coefficientU = projectedV+referenceV;
coefficientV = projectedU+referenceU;
jacobian = [ ...
    coefficientU(:,1).*directionU+coefficientV(:,1).*directionV, ...
    coefficientU(:,2).*directionU+coefficientV(:,2).*directionV, ...
    coefficientU(:,3).*directionU+coefficientV(:,3).*directionV];
end
