function [cineq, ceq] = inequalityOnlyConstraint(beta,x0,y0,z0,B, ...
    rigidityDirections,rigidityReferences,rigidityOffsets,Cchi,Cfold, ...
    r,T,chiMargin,foldAngleMargin)
cineq = ConstraintsGen(beta,x0,y0,z0,B,rigidityDirections, ...
    rigidityReferences,rigidityOffsets,Cchi,Cfold,r,T, ...
    chiMargin,foldAngleMargin);
ceq = [];
end
